# https://megalinter.io/latest/configuration/
CLEAR_REPORT_FOLDER: true
ENABLE:
  - ACTION
  - BASH
  - DOCKERFILE
  - EDITORCONFIG
  - JSON
  # - REPOSITORY
  - YAML
# DISABLE_LINTERS:
#   - JSON_NPM_PACKAGE_JSON_LINT
#   - REPOSITORY_DEVSKIM
#   - REPOSITORY_GITLEAKS # ignores config rules to not lint certain file paths
#   - REPOSITORY_SYFT # generating an unused bill of materials is not necessary
#   - REPOSITORY_SECRETLINT # functionality is covered by checkov
#   - REPOSITORY_KICS # functionality is efficiently covered by hadolint
FAIL_IF_MISSING_LINTER_IN_FLAVOR: true
# FILTER_REGEX_INCLUDE: (.github/|configs/|data/|scripts/|Dockerfile)
FILTER_REGEX_EXCLUDE: (^pnpm-lock\.yaml|node_modules/|logs/|megalinter-reports/|dist/)
REPOSITORY_CHECKOV_UNSECURED_ENV_VARIABLES:
  - CKV_IGNORED_DIRECTORIES=logs
REPOSITORY_CHECKOV_ARGUMENTS: --skip-check MEDIUM
EXCLUDED_DIRECTORIES:
  - .git
  - node_modules
  - logs
  - megalinter-reports
  - dist
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
PRINT_ALPACA: false
FLAVOR_SUGGESTIONS: false
# remove lingering docker containers when done
POST_COMMANDS:
  - command: docker system prune -f
    cwd: "workspace"
    continue_if_failed: true
