---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  - SPELL # Comment to enable checks of spelling mistakes
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
CLEAR_REPORT_FOLDER: true
FILTER_REGEX_EXCLUDE: (pnpm-lock.yaml|node_modules/*|logs/*|megalinter-reports/*)
DISABLE_LINTERS:
  - "MARKDOWN_MARKDOWN_LINK_CHECK"
  - "REPOSITORY_DEVSKIM"
  - "REPOSITORY_GITLEAKS" # takes a very long time to process
  - "REPOSITORY_SYFT" # generating an unused bill of materials is not necessary
# remove lingering docker containers when done
POST_COMMANDS:
  - command: docker system prune -f
    cwd: "workspace"
    continue_if_failed: true
