---
name: 📚 List Maintenance
description: Adding a new list source, blocking specific hosts, manifesto violations, etc.
title: "[list]: "
labels: ["maintenance"]
assignees:
  - T145
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: request
    attributes:
      label: What needs to change?
      description: Anything related to the lists, from host redundancies to new list recommendations.
      placeholder: Details go here!
      value: "Please change this:"
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: If relevant, please include the OS or platform you're using the list(s) on.
      placeholder: ex. Ubuntu 21.04
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/T145/black-mirror/blob/master/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
