verbose = false
no_progress = true
output = "exports/target-status.txt"
exclude-all-private = true
exclude-mail = true
threads = 200
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0"
timeout = 10
retry_wait_time = 0
