name: Automated Targeting System

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate lists
        run: ./scripts/github/automated_targeting_system.bash
        shell: bash

      - name: Update targets
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ✨🎯✨
