name: Auto Merge Dependabot Update

on:
  pull_request:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ahmadnassri/action-dependabot-auto-merge@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
