---
name: Automated Targeting System

on:
  schedule:
    - cron: "0 7 * * *"
  push:
    branches:
      - master
    paths:
      - "data/v1/sources.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
      options: --user root

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set permissions
        run: chmod -R 755 ./scripts/*

      - name: Generate lists
        run: ./scripts/ats/automated_targeting_system.bash

      - name: Update targets
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci(targets): ✨🎯✨"
