name: Create Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Create Builds
        # importing will be performed just before building
        run: |
          :> logs/aria2.log
          chmod 755 -R core/*.bash -R scripts/*.bash -R imports/*.bash -R imports/*.py
          ./core/build.bash
          ./scripts/update_readme.bash
        shell: bash
      - name: Publish Release
        if: success()
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: All Artifacts
          files: build/*
      - name: Remove Artifacts
        if: always()
        run: rm -rf build/
      - name: Update README Statistics
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          # homage to the python linting utility "black"
          commit_message: ✨🍰✨
