name: Clean Old Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Delete workflow runs
        uses: MajorScruffy/delete-workflow-runs
        id: delete-workflow-runs
        with:
          repository: T145/black-mirror
          older-than-seconds: 86400 # remove all workflow runs older than 1 day
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
