---
name: Clean Old Workflows

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  clean:
    runs-on: ubuntu-22.04

    steps:
      - name: Remove expired workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.FOR_WEBHOOKS_SECRET }}
          retain_days: 1
          keep_minimum_runs: 2

      # https://github.com/otto-de/purge-deprecated-workflow-runs
      - name: Remove ancient workflow runs
        uses: otto-de/purge-deprecated-workflow-runs@v1
        with:
          token: ${{ secrets.FOR_WEBHOOKS_SECRET }}
