---
name: Clean Old Data

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: read-all

jobs:
  clean:
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/Mattraks/delete-workflow-runs
      - name: Remove expired workflow runs
        uses: Mattraks/delete-workflow-runs@c3872d103f18a947d291cd2c3c81c90397b4b830
        with:
          token: ${{ secrets.FOR_WEBHOOKS_SECRET }}
          retain_days: 1
          keep_minimum_runs: 2
      # https://github.com/otto-de/purge-deprecated-workflow-runs
      - name: Remove ancient workflow runs
        uses: otto-de/purge-deprecated-workflow-runs@92c76f4e319728cef930489ae0ac7dd5e72e550e
        with:
          token: ${{ secrets.FOR_WEBHOOKS_SECRET }}
          remove-cancelled: true
          remove-skipped: true
