name: Clean Old Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Remove expired workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 2

      - name: Remove deleted workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          keep_minimum_runs: 0
          delete_workflow_pattern: 'Publish Lists to GitHub'

      - name: Remove deleted workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          keep_minimum_runs: 0
          delete_workflow_pattern: 'Publish Lists to Dropbox'

      - name: Remove deleted workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          keep_minimum_runs: 0
          delete_workflow_pattern: 'Create Release'

      - name: Remove deleted workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          keep_minimum_runs: 0
          delete_workflow_pattern: 'Update the Blacklist'
