name: Clean Old Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Remove expired workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.FOR_WEBHOOKS_SECRET }}
          retain_days: 1
          keep_minimum_runs: 2

      - name: Remove ancient workflow runs
        uses: otto-contentfactory/purge-workflow-runs@v1
        with:
          token: ${{ secrets.FOR_WEBHOOKS_SECRET }}
