---
name: Sort Sources

# https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/2
on:
  push:
    branches:
      - master
    paths:
      - "data/v2/lists.json"
  workflow_dispatch:

jobs:
  export_sources:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
      options: --user root

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: git config --global --add safe.directory /__w/black-mirror/black-mirror

      - name: Sort sources
        run: jq -S '.' data/v2/lists.json | sponge data/v2/lists.json

      # https://unix.stackexchange.com/questions/646332/json-to-table-format-using-shell-script
      - name: Export sources
        run: jq -r '["Source", "Method", "Description", "Homepage", "License"], (to_entries[] | .key as $key | .value.method as $method | .value.metadata | [$key, $method, .description, .homepage, .license]) | @csv' data/v2/lists.json | csvlook | sponge SOURCES.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci(sources): ✨📚✨"
