---
name: Publish Manifest

on:
  push:
    branches:
      - master
    paths:
      - "data/v2/lists.json"
  workflow_dispatch:

jobs:
  publish_manifest:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    permissions:
      contents: write

    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
      options: --user root

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Sort manifest
        run: jq -S '.' data/v2/lists.json >data/v2/lists.json
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci(lists): ✨📚✨"
