# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
name: Create Release

on:
  workflow_dispatch:
  schedule:
    - cron: "27 1,13 * * *"

jobs:
  build_release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Create builds
        run: |
          chmod 755 -R scripts/
          ./scripts/workflow.bash
        shell: bash
      - name: Upload build artifacts
        if: success()
        # https://docs.github.com/en/rest/reference/actions#artifacts
        uses: actions/upload-artifact@v3
        with:
          name: black-mirror
          path: build/*
          retention-days: 1
      - name: Upload modified documents
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: black-docs
          path: |
            logs/*
            README.md
            CHANGELOG.md
          retention-days: 1
      - name: Remove local artifacts
        if: always()
        run: rm -rf build/
  publish_github:
    runs-on: ubuntu-latest
    needs: build_release
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: black-mirror
          path: build/
      - name: Create GitHub release & upload build artifacts
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: latest
          prerelease: false
          title: All Artifacts
          files: build/*
      - name: Retry build artifact upload
        if: failure()
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: build/*
          name: All Artifacts
          tag_name: latest
          fail_on_unmatched_files: true
      - name: Remove local build artifacts
        if: always()
        run: rm -rf build/
  publish_dropbox:
    runs-on: ubuntu-latest
    needs: build_release
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: black-mirror
          path: build/
      - name: Upload blacklist checksums
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: build/black_*.checksums
          dest: /black-mirror/
          mode: overwrite
          multiple: true
      - name: Sleep to avoid 429 error
        run: sleep 5s
        shell: bash
      - name: Upload blacklists
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: build/black_*.txt
          dest: /black-mirror/
          mode: overwrite
          multiple: true
      - name: Sleep to avoid 429 error
        run: sleep 5s
        shell: bash
      - name: Upload whitelist checksums
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: build/white_*.checksums
          dest: /black-mirror/
          mode: overwrite
          multiple: true
      - name: Sleep to avoid 429 error
        run: sleep 5s
        shell: bash
      - name: Upload whitelists
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: build/white_*.txt
          dest: /black-mirror/
          mode: overwrite
          multiple: true
      - name: Remove local build artifacts
        if: always()
        run: rm -rf build/
  update_docs:
    runs-on: ubuntu-latest
    needs: [publish_github, publish_dropbox]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download modified documents
        uses: actions/download-artifact@v3
        with:
          name: black-docs
      - name: Update logs and README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # homage to the python linting utility "black"
          commit_message: ✨🍰✨
