---
name: Publish Manifest

on:
  push:
    branches:
      - master
    paths:
      - "data/v2/manifest.json"
  workflow_dispatch:

permissions: read-all

jobs:
  publish_manifest:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    permissions:
      contents: write

    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
      options: --user root

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Sort manifest
        run: |
          jq -S '.' data/v2/manifest.json |
          perl -ne '
          push @lines, $_;
          END {
            open(OUT, ">$file")
            or die "sponge: cannot open $file: $!\n";
            print OUT @lines;
            close(OUT);
          }' -s -- -file=data/v2/manifest.json
      - name: Document manifest
        run: jq -r '["Source", "Method", "Description", "Homepage", "License"], (to_entries[] | .key as $key | .value.method as $method | .value.metadata | [$key, $method, .description, .homepage, .license]) | @csv' data/v2/manifest.json | csvlook >SOURCES.md
      - name: Make commit directory safe
        run: git config --global --add safe.directory /__w/black-mirror/black-mirror
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(lists): ✨📚✨"
