name: Publish Lists to Dropbox

on:
  release:
    types: [released]

jobs:
  dropbox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate output directory
        run: mkdir -p build/

      - name: Download release assets
        uses: robinraju/release-downloader@v1.3
        with:
          repository: "T145/black-mirror"
          latest: true
          fileName: "*"

      - name: Upload blacklist checksums
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: build/black_*.checksums
          dest: /black-mirror/
          mode: overwrite
          multiple: true

      - name: Sleep to avoid 429 error
        run: sleep 5s
        shell: bash

      - name: Upload whitelist checksums
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: build/white_*.checksums
          dest: /black-mirror/
          mode: overwrite
          multiple: true

      - name: Upload blacklists
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: build/black_*.txt
          dest: /black-mirror/
          mode: overwrite
          multiple: true

      - name: Sleep to avoid 429 error
        run: sleep 5s
        shell: bash

      - name: Upload whitelists
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: build/white_*.txt
          dest: /black-mirror/
          mode: overwrite
          multiple: true

      # Just to be clean!
      - name: Remove local artifacts
        if: always()
        run: rm -rf build/
        shell: bash
