name: Create Release

on:
  #repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create_release:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Prepare Workspace
        run: |
          sudo apt install golang-go ipcalc libnet-libidn-perl libnet-idn-encode-perl miller moreutils openjdk-16-jre-headless -y
          # pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint
          chmod 755 -R ./core
          chmod 755 -R ./scripts
        shell: bash

      - name: Sort Sources Alphabetically
        run: |
          jq -S -M '.' core/sources.json > temp.json
          mv temp.json core/sources.json
        shell: bash

      - name: Convert Sources to Pihole Format
        run: jq -jr 'to_entries[] | select(.value.color == "black") | .value.mirrors[0] as $url | .value.filters[] | if (.engine == "cat" or .engine == "mawk") then ($url, " ") else empty end' core/sources.json | sed 's/ $/\n/' >sources/sources.pihole
        shell: bash

      - name: Convert Sources to Text Format
        run: jq -r 'to_entries[].value.mirrors[]' core/sources.json >sources/sources.txt
        shell: bash

      - name: Reset Aria2 Log
        run: |
          rm logs/aria2.log
          touch logs/aria2.log
        shell: bash

      - name: Create Builds
        run: ./core/create_builds.bash
        shell: bash

      - name: Update README.md
        run: ./core/update_readme.bash
        shell: bash

      - name: Publish Release
        if: success()
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: All Artifacts
          files: build/*

      - name: Remove Artifacts
        if: always()
        run: |
          rm -rf build/
          # rm -rf exports/

      - name: Auto Commit
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🔼 Auto Update
