name: Create Release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repo
        uses: "actions/checkout@v2.3.4"
        with:
          ref: ${{ github.head_ref }}

      - name: Fix Script Permissions
        run: chmod 755 -R ./scripts

      - name: Fix Sources
        run: |
          jq -S -M '.' sources.json > temp.json
          mv temp.json sources.json
        shell: bash

      - name: Reset Aria2 Log
        run: |
          rm logs/aria2.log
          touch logs/aria2.log
        shell: bash

      - name: Install Dependencies
        run: sudo apt install aria2 coreutils gawk jq mawk moreutils prips sed
        shell: bash

      - name: Create Builds
        run: ./scripts/create_builds.bash
        shell: bash

      - name: Update README.md
        run: ./scripts/update_readme.bash
        shell: bash

      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Production Builds"
          files: |
            *.tar.gz
            *.md5

      - name: Remove Artifacts
        run: |
          rm *.tar.gz
          rm *.txt
          rm *.md5

      - name: Auto Commit
        uses: "stefanzweifel/git-auto-commit-action@v4.11.0"
        with:
          commit_message: 🔼 Auto Update
