name: Create Release

on:
  #repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create_release:
    runs-on: ubuntu-20.04

    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout latest repo version
        uses: actions/checkout@v2

      - name: Set script permissions
        run: chmod 755 -R ./core -R ./scripts
        shell: bash

      - name: Sort Sources Alphabetically
        run: |
          jq -S -M '.' core/sources.json > temp.json
          mv temp.json core/sources.json
        shell: bash

      - name: Convert Sources to Pihole Format
        run: jq -jr 'to_entries[] | select(.value.color == "black") | .value.mirrors[0] as $url | .value.filters[] | if (.engine == "cat" or .engine == "mawk") then ($url, " ") else empty end' core/sources.json | sed 's/ $/\n/' >sources/sources.pihole
        shell: bash

      - name: Convert Sources to Text Format
        run: jq -r 'to_entries[].value.mirrors[]' core/sources.json >sources/sources.txt
        shell: bash

      - name: Reset Aria2 Log
        run: |
          rm logs/aria2.log
          touch logs/aria2.log
        shell: bash

      - name: Create Builds
        run: ./core/build.bash
        shell: bash

      - name: Update README.md
        run: ./scripts/update_readme.bash
        shell: bash

      - name: Publish Release
        if: success()
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          title: All Artifacts
          files: |
            build/*

      - name: Remove Artifacts
        if: always()
        run: |
          rm -rf build/
          # rm -rf imports/

      - name: Update Changelog
        if: success()
        uses: heinrichreimer/github-changelog-generator-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # https://renehernandez.io/essays/2020/09/23/automate-changelog-and-releases-creation-in-github/#github-action-gotchas
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          unreleased: true
          #addSections: '{"documentation":{"prefix":"**Documentation:**","labels":["documentation"]}}'

      - name: Auto Commit
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🔼 Auto Update
