name: Build Blacklist Release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  apply_fixes:
    runs-on: ubuntu-20.04

    steps:
      - uses: "actions/checkout@v2.3.4"
        with:
          ref: ${{ github.head_ref }}

      - name: Fix Script Permissions
        run: chmod 777 -R ./scripts

      - name: Fix Sources
        run: |
          jq -S -M '.' sources.json > temp.json
          mv temp.json sources.json
        shell: bash

      - name: Auto Commit
        uses: "stefanzweifel/git-auto-commit-action@v4.11.0"
        with:
          commit_message: Applied fixes

  create_release:
    needs: [apply_fixes]
    runs-on: ubuntu-20.04

    steps:
      - uses: "actions/checkout@v2.3.4"
        with:
          ref: ${{ github.head_ref }}

      - name: Install Dependencies
        run: ./scripts/setup.sh
        shell: bash

      - name: Create Builds
        run: ./scripts/build.sh
        shell: bash

      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Production Builds"
          files: |
            *.tar.gz

      - name: Remove Old Releases
        uses: eregon/keep-last-n-releases@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          n: 3
