name: Create Release

on:
  #repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  create_release:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repo
        uses: "actions/checkout@v2.3.4"
        with:
          ref: ${{ github.head_ref }}

      - name: Prepare Workspace
        run: |
          sudo apt update -y
          sudo apt install aria2 gawk ipcalc jq libnet-libidn-perl libnet-idn-encode-perl libtry-tiny-perl mawk miller moreutils sed p7zip-full
          chmod 755 -R ./scripts
        shell: bash

      - name: Fix Sources
        run: |
          jq -S -M '.' sources/sources.json > temp.json
          mv temp.json sources/sources.json
        shell: bash

      - name: Export Sources in Pihole Format
        run: jq -jr 'to_entries[] | select(.value.color == "black") | .value.mirrors[0] as $url | .value.filters[] | if (.engine == "mawk" and .format == "domain") then ($url, " ") else empty end' sources/sources.json | sed 's/ $/\n/' >sources/sources.pihole
        shell: bash

      - name: Export Sources in Text Format
        run: jq -r 'to_entries[].value.mirrors[]' sources/sources.json >sources/sources.txt
        shell: bash

      - name: Reset Aria2 Log
        run: |
          rm logs/aria2.log
          touch logs/aria2.log
        shell: bash

      - name: Create Builds
        run: ./scripts/create_builds.bash
        shell: bash

      - name: Update README.md
        run: ./scripts/update_readme.bash
        shell: bash

      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Production Builds"
          files: |
            *.tar.gz
            *.md5
            *.sha1
            *.sha256

      - name: Remove Artifacts
        run: |
          rm *.tar.gz
          rm *.txt
          rm *.md5
          rm *.sha1
          rm *.sha256

      - name: Auto Commit
        uses: "stefanzweifel/git-auto-commit-action@v4.11.0"
        with:
          commit_message: 🔼 Auto Update
