name: Update the Blacklist

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  update-the-blacklist:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set Script Permissions
        run: |
          chmod 777 ./scripts/setup.sh
          chmod 777 ./scripts/update.sh

      - name: Install Dependencies
        run: ./scripts/setup.sh
        shell: bash

      - name: Sort Sources Alphabetically By Key
        run: jq 'to_entries | sort_by(.key) | from_entries' sources.json >|sources.json
        shell: bash

      - name: Perform Blacklist Update
        run: ./scripts/update.sh
        shell: bash

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: Updated the Blacklist
