---
name: Update Contributions

on:
  push:
    paths:
      - "data/v2/contrib/*"
  workflow_dispatch:

permissions: read-all

jobs:
  publish_manifest:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
      options: --user root
    steps:
      - name: Checkout repo
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f
      - name: Update contribution lists
        run: |
          mawk '/^[^[:space:]|^#|]/' data/v2/contrib/DOMAIN_WHITELIST.txt | subfinder -silent -nc | dnsx -silent -nc >>dist/CONTRIB_DOMAINS.txt
          sort -o dist/CONTRIB_DOMAINS.txt -u dist/CONTRIB_DOMAINS.txt
      - name: Make commit directory safe
        run: git config --global --add safe.directory /__w/black-mirror/black-mirror
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@4b8a201e31cadd9829df349894b28c54e6c19fe6
        with:
          commit_message: "ci(contrib): ✨📚✨"
