name: Update Sources

# https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/2
on:
  push:
    branches:
      - master
    paths:
      - "data/v1/sources.json"

jobs:
  export_sources:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Export sources
        run: |
          jq -SM '.' data/v1/sources.json | sponge data/v1/sources.json
          jq -jr 'to_entries[] | select(.value.color == "black") | .value.mirrors[0] as $url | .value.filters[] | if (.engine == "cat" or .engine == "mawk") then ($url, " ") else empty end' data/v1/sources.json | sed 's/ $/\n/' >exports/sources.pihole
          jq -r 'to_entries[].value.mirrors[]' data/v1/sources.json >exports/sources.txt
          parsort -u -S 100% --parallel=48 exports/sources.txt | sponge exports/sources.txt
        shell: bash
      - name: Upload modified sources
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: black-sources
          path: |
            data/v1/sources.json
            exports/*
          retention-days: 1
  commit_changes:
    runs-on: ubuntu-latest
    needs: export_sources
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download Modified Sources
        uses: actions/download-artifact@v3
        with:
          name: black-sources
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: ✨📚✨
