name: Update Sources

# https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/2
on:
  push:
    branches:
      - master
    paths:
      - "data/v2/lists.json"
  workflow_dispatch:

jobs:
  export_sources:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Export sources
        run: |
          jq -SM '.' data/v2/lists.json | sponge data/v2/lists.json
          jq -jr 'to_entries[] | select(.value.method == "BLOCK" and .value.variants.pihole != null) | (.value.variants.pihole, " ")' data/v2/lists.json | sed 's/ $/\n/' >exports/sources.pihole
          jq -r 'to_entries[].value.mirrors[]' data/v2/lists.json >exports/sources.txt
          parsort -u -S 100% --parallel=48 exports/sources.txt | sponge exports/sources.txt
        shell: bash

      - name: Upload modified sources
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: lists
          path: |
            data/v2/lists.json
            exports/*
          retention-days: 1

  commit_changes:
    runs-on: ubuntu-latest
    needs: export_sources
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download modified Sources
        uses: actions/download-artifact@v3
        with:
          name: lists

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ✨📚✨
