name: Update Sources

# https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/2
on:
  push:
    branches:
      - master
    paths:
      - "data/v2/lists.json"
  workflow_dispatch:

jobs:
  export_sources:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Export sources
        run: |
          git config --global --add safe.directory /__w/black-mirror/black-mirror
          jq -SM '.' data/v2/lists.json | sponge data/v2/lists.json
          jq -jr 'to_entries[] | select(.value.method == "BLOCK" and .value.variants.pihole != null) | (.value.variants.pihole, " ")' data/v2/lists.json | sed 's/ $/\n/' >exports/sources.pihole
          jq -jr 'to_entries[] | select(.value.method == "BLOCK" and .value.variants.adguard != null) | ("!#include ", .value.variants.adguard, "\n")' data/v2/lists.json >exports/sources.adguard
          jq -r 'to_entries[].value.mirrors[]' data/v2/lists.json | sponge exports/sources.txt
          jq -r 'to_entries[] | select(.value.variants != null) | .value.variants | to_entries[].url' data/v2/lists.json >>exports/sources.txt
          parsort -bfiu -S 100% --parallel=200 exports/sources.txt | sponge exports/sources.txt
        shell: bash

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ✨📚✨
