name: Update Sources

# https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/2
on:
  push:
    branches:
      - master
    paths:
      - 'core/sources.json'

jobs:
  update:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Convert Sources
        run: |
          jq -SM '.' core/sources.json | sponge core/sources.json
          jq -jr 'to_entries[] | select(.value.color == "black") | .value.mirrors[0] as $url | .value.filters[] | if (.engine == "cat" or .engine == "mawk") then ($url, " ") else empty end' core/sources.json | sed 's/ $/\n/' >sources/sources.pihole
          jq -r 'to_entries[].value.mirrors[]' core/sources.json >sources/sources.txt
        shell: bash
      - name: Update Sources
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: 📚 Updated Sources
